# Generated by Django 5.0.3 on 2024-04-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_rename_product_id_order_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
